# Generated by Django 6.0.5 on 2026-05-14 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='compliance__company_bbf714_idx',
            old_name='comp_audit_co_tl_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='compliance__employe_f4e8ae_idx',
            old_name='comp_audit_emp_ts_idx',
        ),
    ]
