# Generated by Django 6.0.5 on 2026-05-14 06:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_employee_compliance_fields'),
        ('time_tracking', '0005_remove_location_loc_polygon_gin_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='timelog',
            index=models.Index(fields=['status', 'work_date'], name='tl_status_date_idx'),
        ),
        migrations.AddIndex(
            model_name='timelog',
            index=models.Index(fields=['employee', 'status'], name='tl_emp_status_idx'),
        ),
    ]
