# Generated by Django 6.0.5 on 2026-05-14 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_employee_compliance_fields'),
        ('live_locations', '0002_geofencebreach_sosalert'),
        ('time_tracking', '0005_remove_location_loc_polygon_gin_idx_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='geofencebreach',
            new_name='live_locati_employe_ac8113_idx',
            old_name='live_loc_breach_emp_ts_idx',
        ),
        migrations.RenameIndex(
            model_name='sosalert',
            new_name='live_locati_employe_6c56a7_idx',
            old_name='live_loc_sos_emp_ts_idx',
        ),
        migrations.RenameIndex(
            model_name='sosalert',
            new_name='live_locati_status_b1d6c5_idx',
            old_name='live_loc_sos_status_idx',
        ),
        migrations.AddIndex(
            model_name='employeelocation',
            index=models.Index(fields=['time_log', 'timestamp'], name='live_locati_time_lo_b6c3a3_idx'),
        ),
    ]
